# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f85d65b508f14bd72ea85e8149e35fa20dafdaa03969750be42ce488c4cc70399c2f82469b84f888beca1bff6ad5f9d0fca0080cba0682745f8c5100bf63aaa

test:
  secret_key_base: c9f324f92e499a57211d3dd43c3d25b1e52d082538742c59035fc0ff5a8d7e45bb1cde32e30a52da8a9baf103105109439d7e70d047f90630d88994aa77e8a0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
